"""Labelled medical record number (MRN) recognizer, tolerant of one OCR error in the label.

Problem. Presidio ships no MRN recognizer. This project's first attempt scored a bare
6-10 digit run at 0.4 against the 0.5 threshold, so MRNs were never scrubbed (CHANGELOG
2026-09-03). Anchoring on the field label fixes that and, because the label sits in a
lookbehind, only the digits are replaced: ``MRN: 1234567`` becomes ``MRN: <MRN_1>`` and the
model still sees which field it was. The exact-label anchor then left one gap: Tesseract read
``MRN:`` as ``MAN:`` on a scanned page and the seven-digit number survived, the single
survivor behind the 0.992 de-id recall on the OCR corpus (CHANGELOG 2026-09-04, TODO item 14).

Scores.
    ``mrn_labeled`` 0.85: ``MRN`` followed by ``: ``, ``:``, a space, ``# `` or ``#`` and 6-10
    digits (Python lookbehinds must be fixed-width, hence one alternative per spelling).
    ``mrn_label_ocr`` 0.7: the same, with the label replaced by any edit-distance-1 variant
    (one letter substituted or deleted: ``MAN``, ``MRM``, ``RN``, ``MR``, ...) or a spacing
    variant (``M R N``, ``M RN``, ``MR N``); generated by :func:`label_variants`, grouped by
    width so each lookbehind stays fixed-width. Lower than the exact label because ``MR``,
    ``RN`` and ``MRS`` are also words, but still above the 0.5 threshold on their own.
    ``mrn_demographics_line`` 0.5: a bare 6-10 digit run on a line that also carries a
    demographics cue (``DOB``, ``Patient``, ``Name``, ``Sex``, ``Age``), the fallback for a
    label OCR mangled beyond one edit. Exactly at threshold. It cannot fire on a formatted date
    (``03/05/2024``), a phone number (``555-0100``), a ZIP (``75001``) or a five-digit lab value
    (``WBC 11000``) because none of those contains six consecutive digits; a six-digit lab value
    such as a platelet count written ``250000`` on the demographics line would be taken.
    ``mrn_bare`` 0.3: any 6-10 digit run, below threshold alone, lifted to 0.65 by Presidio's
    context enhancer (+0.35) when ``mrn``, ``medical record``, ``record number`` or ``chart
    number`` appears in the words before it.

Examples (tests/test_recognizers.py). ``MRN: 1234567``, ``MRN:1234567``, ``MRN 1234567``,
``MRN# 1234567``, ``MRN#1234567`` and ``MRN: 1234567890`` each give one MRN span over the digits
only, score 0.85. ``MAN: 1234567``, ``MRM 1234567`` and ``M R N: 1234567`` give the same span
at 0.7. ``Patient: John Doe   1234567   DOB 01/02/1960`` gives ``1234567`` at 0.5. In
``MRN 9218993518 and phone 921-899-3518 ext 7`` the digit run inside the phone number is also
an ``mrn_bare`` candidate; the caller's overlap resolution merges it into the phone span.
"""
import re
from typing import List, Optional

from presidio_analyzer import EntityRecognizer, Pattern, PatternRecognizer, RecognizerResult

NAME = "mrn_regex"
LABELS = ("MRN",)
SEPARATORS = (": ", ":", " ", "# ", "#")
CONTEXT = ["mrn", "medical record", "record number", "chart number"]
DEMOGRAPHICS_CUES = ("DOB", "Patient", "Name", "Sex", "Age")

_DIGITS = r"\d{6,10}\b"
_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
_CUE = re.compile(r"\b(?:" + "|".join(DEMOGRAPHICS_CUES) + r")\b", re.IGNORECASE)
_RUN = re.compile(r"\b" + _DIGITS)


def label_variants(label: str) -> set:
    """Edit-distance-1 variants of a label (one letter substituted or deleted; no insertions)
    plus its spacing variants (a space in any subset of the gaps between letters). The label
    itself is not included. ``MRN`` gives 75 substitutions, 3 deletions and 3 spacings."""
    out = set()
    for i, ch in enumerate(label):
        out.add(label[:i] + label[i + 1:])
        out.update(label[:i] + c + label[i + 1:] for c in _ALPHABET if c != ch)
    gaps = len(label) - 1
    for mask in range(1, 1 << gaps):
        spaced = label[0]
        for i in range(gaps):
            spaced += (" " if mask >> i & 1 else "") + label[i + 1]
        out.add(spaced)
    out.discard(label)
    return out


def _labelled_regex(labels) -> str:
    """One fixed-width lookbehind per (label width, separator): only the digits are matched."""
    by_width: dict = {}
    for label in labels:
        by_width.setdefault(len(label), set()).add(label)
    alts = []
    for width in sorted(by_width):
        group = "|".join(re.escape(l) for l in sorted(by_width[width]))
        for sep in SEPARATORS:
            alts.append(rf"(?<=\b(?:{group}){re.escape(sep)}){_DIGITS}")
    return "|".join(alts)


class MrnRecognizer(PatternRecognizer):
    """Labelled MRNs (exact and OCR-damaged labels) plus the demographics-line fallback."""

    def __init__(self, supported_language: str = "en"):
        ocr = set()
        for label in LABELS:
            ocr |= label_variants(label)
        patterns = [Pattern("mrn_labeled", _labelled_regex(LABELS), 0.85),
                    Pattern("mrn_label_ocr", _labelled_regex(sorted(ocr)), 0.7),
                    # bare 6-10 digit run: weak alone; Presidio's context enhancer lifts it when
                    # 'mrn' / 'medical record' appears nearby.
                    Pattern("mrn_bare", r"\b" + _DIGITS, 0.3)]
        super().__init__(supported_entity="MRN", name=NAME, patterns=patterns,
                         context=CONTEXT, supported_language=supported_language)

    def analyze(self, text: str, entities: List[str], nlp_artifacts=None,
                regex_flags: Optional[int] = None) -> List[RecognizerResult]:
        results = super().analyze(text, entities, nlp_artifacts, regex_flags)
        results.extend(self._demographics_line(text))
        return EntityRecognizer.remove_duplicates(results)

    def _demographics_line(self, text: str) -> List[RecognizerResult]:
        """A bare 6-10 digit run scores 0.5 when its line also carries a demographics cue."""
        out, offset = [], 0
        for line in text.split("\n"):
            if _CUE.search(line):
                for m in _RUN.finditer(line):
                    explanation = self.build_regex_explanation(
                        self.name, "mrn_demographics_line", _RUN.pattern, 0.5, None, re.IGNORECASE)
                    out.append(RecognizerResult(
                        entity_type="MRN", start=offset + m.start(), end=offset + m.end(), score=0.5,
                        analysis_explanation=explanation,
                        recognition_metadata={RecognizerResult.RECOGNIZER_NAME_KEY: self.name,
                                              RecognizerResult.RECOGNIZER_IDENTIFIER_KEY: self.id}))
            offset += len(line) + 1
        return out


def mrn_recognizer() -> MrnRecognizer:
    return MrnRecognizer()
